<template><h1 id="html-css-javascript"><a class="header-anchor" href="#html-css-javascript">#</a> HTML + CSS + JavaScript</h1>
<p>ajax.md
axios.md
call.md
copy-deep.md
currying.md
extend.md
instanceof.md
object-create.md
promise.md
sleep.md
apply.md
bind.md
class.md
copy-shadow.md
debounce.md
flat.md
new.md
pipe.md
reduce.md</p>
<p>['ajax.md',
'axios.md',
'call.md',
'copy-deep.md',
'currying.md',
'extend.md',
'instanceof.md',
'objectcreate.md',
'promise.md',
'sleep.md',
'apply.md',
'bind.md',
'class.md',
'copy-shadow.md',
'debounce.md',
'flat.md',
'new.md',
'pipe.md',
'reduce.md']</p>
</template>